spring.application.name=rag-java-advanced

# ==========================================================
# POSTGRESQL
# ==========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=rag
spring.datasource.password=rag

# ==========================================================
# FLYWAY
# ==========================================================

spring.flyway.enabled=true

# ==========================================================
# OLLAMA
# ==========================================================

spring.ai.ollama.base-url=http://localhost:11434

# LLM
spring.ai.ollama.chat.model=qwen3:4b

# Embedding
spring.ai.ollama.embedding.model=qwen3-embedding:0.6b

# ==========================================================
# PGVECTOR
# ==========================================================

spring.ai.vectorstore.pgvector.initialize-schema=true

# ==========================================================
# SERVER
# ==========================================================

server.port=8080