services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: rag-postgres

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: rag-ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data: